<?php

namespace Database\Seeders;

use App\Models\EnvSetting;
use Illuminate\Database\Seeder;

class EnvSettingSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $settings = [
            // Général
            [
                'key' => 'APP_NAME',
                'label' => 'Nom de l\'application',
                'group' => 'general',
                'description' => 'Nom affiché dans l\'application',
                'type' => 'string',
                'is_sensitive' => false,
                'is_editable' => true,
                'sort_order' => 1,
            ],
            [
                'key' => 'APP_ENV',
                'label' => 'Environnement',
                'group' => 'general',
                'description' => 'Environnement d\'exécution (local, production, staging)',
                'type' => 'string',
                'is_sensitive' => false,
                'is_editable' => true,
                'sort_order' => 2,
            ],
            [
                'key' => 'APP_DEBUG',
                'label' => 'Mode debug',
                'group' => 'general',
                'description' => 'Activer le mode debug pour le développement',
                'type' => 'bool',
                'is_sensitive' => false,
                'is_editable' => true,
                'sort_order' => 3,
            ],
            [
                'key' => 'APP_URL',
                'label' => 'URL de l\'application',
                'group' => 'general',
                'description' => 'URL principale de l\'application',
                'type' => 'string',
                'is_sensitive' => false,
                'is_editable' => true,
                'sort_order' => 4,
            ],
            [
                'key' => 'APP_LOCALE',
                'label' => 'Langue par défaut',
                'group' => 'general',
                'description' => 'Langue par défaut de l\'application',
                'type' => 'string',
                'is_sensitive' => false,
                'is_editable' => true,
                'sort_order' => 5,
            ],

            // Base de données
            [
                'key' => 'DB_CONNECTION',
                'label' => 'Connexion DB',
                'group' => 'database',
                'description' => 'Type de connexion de base de données',
                'type' => 'string',
                'is_sensitive' => false,
                'is_editable' => true,
                'sort_order' => 10,
            ],
            [
                'key' => 'DB_HOST',
                'label' => 'Hôte DB',
                'group' => 'database',
                'description' => 'Adresse du serveur de base de données',
                'type' => 'string',
                'is_sensitive' => false,
                'is_editable' => true,
                'sort_order' => 11,
            ],
            [
                'key' => 'DB_PORT',
                'label' => 'Port DB',
                'group' => 'database',
                'description' => 'Port du serveur de base de données',
                'type' => 'int',
                'is_sensitive' => false,
                'is_editable' => true,
                'sort_order' => 12,
            ],
            [
                'key' => 'DB_DATABASE',
                'label' => 'Nom de la base',
                'group' => 'database',
                'description' => 'Nom de la base de données',
                'type' => 'string',
                'is_sensitive' => false,
                'is_editable' => true,
                'sort_order' => 13,
            ],
            [
                'key' => 'DB_USERNAME',
                'label' => 'Utilisateur DB',
                'group' => 'database',
                'description' => 'Nom d\'utilisateur de la base de données',
                'type' => 'string',
                'is_sensitive' => true,
                'is_editable' => true,
                'sort_order' => 14,
            ],
            [
                'key' => 'DB_PASSWORD',
                'label' => 'Mot de passe DB',
                'group' => 'database',
                'description' => 'Mot de passe de la base de données',
                'type' => 'string',
                'is_sensitive' => true,
                'is_editable' => true,
                'sort_order' => 15,
            ],

            // Mail
            [
                'key' => 'MAIL_MAILER',
                'label' => 'Driver mail',
                'group' => 'mail',
                'description' => 'Driver d\'envoi d\'emails',
                'type' => 'string',
                'is_sensitive' => false,
                'is_editable' => true,
                'sort_order' => 20,
            ],
            [
                'key' => 'MAIL_HOST',
                'label' => 'Hôte SMTP',
                'group' => 'mail',
                'description' => 'Adresse du serveur SMTP',
                'type' => 'string',
                'is_sensitive' => false,
                'is_editable' => true,
                'sort_order' => 21,
            ],
            [
                'key' => 'MAIL_PORT',
                'label' => 'Port SMTP',
                'group' => 'mail',
                'description' => 'Port du serveur SMTP',
                'type' => 'int',
                'is_sensitive' => false,
                'is_editable' => true,
                'sort_order' => 22,
            ],
            [
                'key' => 'MAIL_USERNAME',
                'label' => 'Utilisateur SMTP',
                'group' => 'mail',
                'description' => 'Nom d\'utilisateur SMTP',
                'type' => 'string',
                'is_sensitive' => true,
                'is_editable' => true,
                'sort_order' => 23,
            ],
            [
                'key' => 'MAIL_PASSWORD',
                'label' => 'Mot de passe SMTP',
                'group' => 'mail',
                'description' => 'Mot de passe SMTP',
                'type' => 'string',
                'is_sensitive' => true,
                'is_editable' => true,
                'sort_order' => 24,
            ],
            [
                'key' => 'MAIL_ENCRYPTION',
                'label' => 'Encryption SMTP',
                'group' => 'mail',
                'description' => 'Méthode d\'encryption SMTP',
                'type' => 'string',
                'is_sensitive' => false,
                'is_editable' => true,
                'sort_order' => 25,
            ],
            [
                'key' => 'MAIL_FROM_ADDRESS',
                'label' => 'Adresse expéditeur',
                'group' => 'mail',
                'description' => 'Adresse email d\'envoi par défaut',
                'type' => 'string',
                'is_sensitive' => false,
                'is_editable' => true,
                'sort_order' => 26,
            ],
            [
                'key' => 'MAIL_FROM_NAME',
                'label' => 'Nom expéditeur',
                'group' => 'mail',
                'description' => 'Nom de l\'expéditeur par défaut',
                'type' => 'string',
                'is_sensitive' => false,
                'is_editable' => true,
                'sort_order' => 27,
            ],

            // Cache
            [
                'key' => 'CACHE_DRIVER',
                'label' => 'Driver cache',
                'group' => 'cache',
                'description' => 'Driver de cache',
                'type' => 'string',
                'is_sensitive' => false,
                'is_editable' => true,
                'sort_order' => 30,
            ],
            [
                'key' => 'REDIS_HOST',
                'label' => 'Hôte Redis',
                'group' => 'cache',
                'description' => 'Adresse du serveur Redis',
                'type' => 'string',
                'is_sensitive' => false,
                'is_editable' => true,
                'sort_order' => 31,
            ],
            [
                'key' => 'REDIS_PASSWORD',
                'label' => 'Mot de passe Redis',
                'group' => 'cache',
                'description' => 'Mot de passe Redis',
                'type' => 'string',
                'is_sensitive' => true,
                'is_editable' => true,
                'sort_order' => 32,
            ],
            [
                'key' => 'REDIS_PORT',
                'label' => 'Port Redis',
                'group' => 'cache',
                'description' => 'Port du serveur Redis',
                'type' => 'int',
                'is_sensitive' => false,
                'is_editable' => true,
                'sort_order' => 33,
            ],

            // Queue
            [
                'key' => 'QUEUE_CONNECTION',
                'label' => 'Connexion queue',
                'group' => 'queue',
                'description' => 'Driver de queue',
                'type' => 'string',
                'is_sensitive' => false,
                'is_editable' => true,
                'sort_order' => 40,
            ],

            // Sécurité
            [
                'key' => 'APP_KEY',
                'label' => 'Clé application',
                'group' => 'security',
                'description' => 'Clé de chiffrement de l\'application',
                'type' => 'string',
                'is_sensitive' => true,
                'is_editable' => false,
                'sort_order' => 50,
            ],

            // Ringover
            [
                'key' => 'RINGOVER_API_TOKEN',
                'label' => 'Token API Ringover',
                'group' => 'third_party',
                'description' => 'Clé API Ringover pour l\'intégration téléphonie',
                'type' => 'string',
                'is_sensitive' => true,
                'is_editable' => true,
                'sort_order' => 60,
            ],
            [
                'key' => 'RINGOVER_REGION',
                'label' => 'Région Ringover',
                'group' => 'third_party',
                'description' => 'Région de l\'API Ringover (europe ou us)',
                'type' => 'string',
                'is_sensitive' => false,
                'is_editable' => true,
                'sort_order' => 61,
            ],
            [
                'key' => 'RINGOVER_MONITORING_ENABLED',
                'label' => 'Monitoring Ringover activé',
                'group' => 'third_party',
                'description' => 'Active le monitoring Ringover pour accès étendu aux données d\'équipe',
                'type' => 'bool',
                'is_sensitive' => false,
                'is_editable' => true,
                'sort_order' => 62,
            ],
            [
                'key' => 'RINGOVER_WEBHOOK_SECRET',
                'label' => 'Secret Webhook Ringover',
                'group' => 'third_party',
                'description' => 'Secret pour valider les webhooks Ringover entrants',
                'type' => 'string',
                'is_sensitive' => true,
                'is_editable' => true,
                'sort_order' => 63,
            ],
            [
                'key' => 'RINGOVER_TIMEOUT',
                'label' => 'Timeout API Ringover',
                'group' => 'third_party',
                'description' => 'Délai d\'attente maximum pour les requêtes API Ringover (secondes)',
                'type' => 'int',
                'is_sensitive' => false,
                'is_editable' => true,
                'sort_order' => 64,
            ],

            // Laravel Reverb
            [
                'key' => 'REVERB_APP_ID',
                'label' => 'ID Application Reverb',
                'group' => 'third_party',
                'description' => 'ID de l\'application Laravel Reverb pour WebSocket',
                'type' => 'string',
                'is_sensitive' => false,
                'is_editable' => true,
                'sort_order' => 70,
            ],
            [
                'key' => 'REVERB_APP_KEY',
                'label' => 'Clé Application Reverb',
                'group' => 'third_party',
                'description' => 'Clé de l\'application Laravel Reverb',
                'type' => 'string',
                'is_sensitive' => true,
                'is_editable' => true,
                'sort_order' => 71,
            ],
            [
                'key' => 'REVERB_APP_SECRET',
                'label' => 'Secret Application Reverb',
                'group' => 'third_party',
                'description' => 'Secret de l\'application Laravel Reverb',
                'type' => 'string',
                'is_sensitive' => true,
                'is_editable' => true,
                'sort_order' => 72,
            ],
            [
                'key' => 'REVERB_HOST',
                'label' => 'Hôte Reverb',
                'group' => 'third_party',
                'description' => 'Adresse du serveur Laravel Reverb',
                'type' => 'string',
                'is_sensitive' => false,
                'is_editable' => true,
                'sort_order' => 73,
            ],
            [
                'key' => 'REVERB_PORT',
                'label' => 'Port Reverb',
                'group' => 'third_party',
                'description' => 'Port du serveur Laravel Reverb (par défaut 8080)',
                'type' => 'int',
                'is_sensitive' => false,
                'is_editable' => true,
                'sort_order' => 74,
            ],
            [
                'key' => 'REVERB_SCHEME',
                'label' => 'Schéma Reverb',
                'group' => 'third_party',
                'description' => 'Protocole de connexion Reverb (http ou https)',
                'type' => 'string',
                'is_sensitive' => false,
                'is_editable' => true,
                'sort_order' => 75,
            ],
        ];

        foreach ($settings as $setting) {
            EnvSetting::updateOrCreate(
                ['key' => $setting['key']],
                $setting
            );
        }
    }
}
