#!/usr/bin/env php
<?php

use Illuminate\Foundation\Application;
use Symfony\Component\Console\Input\ArgvInput;

define('LARAVEL_START', microtime(true));

// Set custom temp directory to avoid permission issues with system /tmp
@putenv('TMPDIR=' . realpath(__DIR__.'/storage/tmp'));
ini_set('upload_tmp_dir', realpath(__DIR__.'/storage/tmp'));

// Register the Composer autoloader...
require __DIR__.'/vendor/autoload.php';

// Bootstrap Laravel and handle the command...
/** @var Application $app */
$app = require_once __DIR__.'/bootstrap/app.php';

$status = $app->handleCommand(new ArgvInput);

exit($status);
