<link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css">
<style>
#crm-map { min-height: 560px; }
#crm-map .leaflet-pane, #crm-map .leaflet-control, #crm-map .leaflet-top, #crm-map .leaflet-bottom { position: absolute; }
#crm-map .leaflet-container { height: 100%; width: 100%; overflow: hidden; }
#crm-map .leaflet-tile-pane, #crm-map .leaflet-overlay-pane, #crm-map .leaflet-shadow-pane, #crm-map .leaflet-marker-pane, #crm-map .leaflet-tooltip-pane, #crm-map .leaflet-popup-pane { position: absolute; inset: 0; }
</style>
<script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js" integrity="sha256-20nQCchB9co0qIjJZRGuk2/Z9VM+kNiyxNV1lvTlZBo=" crossorigin="anonymous"></script>
@php($mapData = ['departments' => $departments, 'cities' => $cities])
<script type="application/json" id="crm-map-data">@json($mapData ?? [])</script>
<div id="crm-map-app" class="space-y-6">
    <div class="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p class="text-sm font-medium text-primary-600">Vue géographique</p><h2 class="mt-1 text-2xl font-semibold tracking-tight text-gray-950 dark:text-white">Carte CRM</h2><p class="mt-1 text-sm text-gray-500 dark:text-gray-400">Répartition des prospects, clients et partenaires par département et par ville.</p></div><button id="crm-map-reset" type="button" class="rounded-lg border border-gray-300 px-4 py-2 text-sm font-semibold text-gray-700 transition hover:bg-gray-50 dark:border-gray-600 dark:text-gray-200 dark:hover:bg-gray-700">Réinitialiser</button></div>
    <div class="flex flex-wrap gap-2 text-xs"><button data-type="prospects" class="crm-map-type rounded-full bg-blue-50 px-3 py-1.5 font-medium text-blue-700 ring-2 ring-blue-500 dark:bg-blue-500/10 dark:text-blue-300">Prospects</button><button data-type="clients" class="crm-map-type rounded-full bg-emerald-50 px-3 py-1.5 font-medium text-emerald-700 ring-2 ring-emerald-500 dark:bg-emerald-500/10 dark:text-emerald-300">Clients</button><button data-type="partenaires" class="crm-map-type rounded-full bg-amber-50 px-3 py-1.5 font-medium text-amber-700 ring-2 ring-amber-500 dark:bg-amber-500/10 dark:text-amber-300">Partenaires</button></div>
    <div id="crm-map-kpis" class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"></div>
    <section class="rounded-xl bg-white p-4 shadow-sm ring-1 ring-gray-200/60 dark:bg-gray-800/60 dark:ring-gray-700/60"><div class="grid gap-4 md:grid-cols-2"><label class="block"><span class="text-xs font-medium uppercase tracking-wide text-gray-500">Département</span><select id="crm-map-department" class="mt-1 block w-full rounded-lg border-gray-300 text-sm dark:border-gray-600 dark:bg-gray-900"><option value="">Tous les départements</option></select></label><label class="block"><span class="text-xs font-medium uppercase tracking-wide text-gray-500">Ville</span><input id="crm-map-city" list="crm-map-city-options" placeholder="Rechercher une ville…" class="mt-1 block w-full rounded-lg border-gray-300 text-sm dark:border-gray-600 dark:bg-gray-900"><datalist id="crm-map-city-options"></datalist></label></div><p id="crm-map-scope" class="mt-3 text-xs text-gray-500"></p></section>
    <div class="grid gap-6 xl:grid-cols-5"><section class="rounded-xl bg-white p-4 shadow-sm ring-1 ring-gray-200/60 xl:col-span-3 dark:bg-gray-800/60 dark:ring-gray-700/60"><div class="mb-3 flex items-center justify-between"><div><h3 class="font-semibold text-gray-950 dark:text-white">Répartition géographique</h3><p class="text-sm text-gray-500">Cliquez sur un département pour filtrer.</p></div></div><div id="crm-map" class="h-[560px] w-full overflow-hidden rounded-lg"></div></section><section class="rounded-xl bg-white p-4 shadow-sm ring-1 ring-gray-200/60 xl:col-span-2 dark:bg-gray-800/60 dark:ring-gray-700/60"><div class="mb-4"><h3 class="font-semibold text-gray-950 dark:text-white">Départements</h3><p class="text-sm text-gray-500">Les zones les plus représentées.</p></div><div id="crm-map-departments" class="space-y-3"></div></section></div>
    <section class="rounded-xl bg-white p-4 shadow-sm ring-1 ring-gray-200/60 dark:bg-gray-800/60 dark:ring-gray-700/60"><div class="mb-4"><h3 class="font-semibold text-gray-950 dark:text-white">Villes couvertes</h3><p class="text-sm text-gray-500">Sélectionnez une ville pour la localiser.</p></div><div id="crm-map-cities" class="grid gap-2 sm:grid-cols-2 lg:grid-cols-4"></div></section>
</div>
<script>
(() => {
    const root = document.getElementById('crm-map-app'); if (!root || typeof L === 'undefined') return;
    let data = JSON.parse(document.getElementById('crm-map-data')?.textContent || '{}');
    let refreshing = false;
    const state = { department: '', city: '', types: { prospects: true, clients: true, partenaires: true }, map: null, layer: null, marker: null };
    const nf = new Intl.NumberFormat('fr-FR'), esc = (v) => String(v ?? '').replace(/[&<>"']/g, (c) => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
    const types = () => Object.keys(state.types).filter((type) => state.types[type]);
    const match = (row) => types().some((type) => Number(row[type] || 0) > 0);
    const departments = () => (data.departments || []).filter((row) => match(row) && (!state.department || row.label === state.department));
    const cities = () => (data.cities || []).filter((row) => match(row) && (!state.department || row.department === state.department) && (!state.city || row.label.toLowerCase().includes(state.city.toLowerCase())));
    const count = (row) => types().reduce((sum, type) => sum + Number(row[type] || 0), 0);
    const render = () => { const visibleDepartments = departments(), visibleCities = cities(), total = visibleDepartments.reduce((sum, row) => sum + count(row), 0); document.getElementById('crm-map-kpis').innerHTML = [['Entités visibles', total, 'blue'], ['Départements', visibleDepartments.length, 'violet'], ['Villes', visibleCities.length, 'emerald'], ['Périmètre', state.department || 'France', 'amber']].map(([label, value, tone]) => `<article class="rounded-xl bg-white p-5 shadow-sm ring-1 ring-gray-200/60 dark:bg-gray-800/60 dark:ring-gray-700/60"><div class="text-sm text-gray-500">${label}</div><div class="mt-2 text-2xl font-bold text-gray-950 dark:text-white">${typeof value === 'number' ? nf.format(value) : esc(value)}</div><div class="mt-1 text-xs text-gray-400">${tone === 'amber' ? 'Zone active' : 'Après filtres'}</div></article>`).join('');
        const max = Math.max(1, ...visibleDepartments.map((row) => count(row))); document.getElementById('crm-map-departments').innerHTML = visibleDepartments.slice(0, 16).map((row) => `<button data-department="${esc(row.label)}" class="w-full text-left"><div class="mb-1 flex justify-between text-sm"><span class="font-medium text-gray-700 dark:text-gray-200">${esc(row.label)}</span><span class="font-semibold text-gray-950 dark:text-white">${nf.format(count(row))}</span></div><div class="h-2 rounded-full bg-gray-100 dark:bg-gray-700"><div class="h-full rounded-full bg-primary-500" style="width:${Math.max(4, count(row) / max * 100)}%"></div></div></button>`).join('') || '<p class="text-sm text-gray-500">Aucun département.</p>';
        document.getElementById('crm-map-cities').innerHTML = visibleCities.slice(0, 40).map((row) => `<button data-city="${esc(row.label)}" class="rounded-lg border border-gray-200 px-3 py-2 text-left transition hover:border-primary-400 hover:bg-primary-50 dark:border-gray-700 dark:hover:bg-gray-700"><div class="truncate text-sm font-medium text-gray-800 dark:text-gray-200">${esc(row.label)}</div><div class="mt-1 text-xs text-gray-500">${esc(row.department || 'NC')} · ${nf.format(count(row))} entités</div></button>`).join('') || '<p class="text-sm text-gray-500">Aucune ville.</p>';
        document.getElementById('crm-map-scope').textContent = `${state.department ? 'Département ' + state.department : 'France entière'} · ${types().length === 3 ? 'Tous les types' : types().join(', ')}`;
        refreshLayer();
    };
    const style = (feature) => { const code = feature.properties.code || feature.properties.nom || ''; const row = (data.departments || []).find((item) => item.label === code); const max = Math.max(1, ...(data.departments || []).map((item) => item.total || 0)); const total = row ? row.total : 0; return { color: state.department === code ? '#0f172a' : '#64748b', weight: state.department === code ? 3 : 1, fillColor: '#2563eb', fillOpacity: total ? 0.18 + Math.min(total / max, 1) * 0.55 : 0.04 }; };
    const refreshLayer = () => { if (state.layer) state.layer.setStyle(style); };
    const geocode = async () => { const row = (data.cities || []).find((item) => item.label.toLowerCase() === state.city.toLowerCase() && (!state.department || item.department === state.department)); if (!row) return; try { const params = new URLSearchParams({ q: row.label, limit: '1', autocomplete: '0' }); const response = await fetch('https://api-adresse.data.gouv.fr/search/?' + params); const feature = (await response.json()).features?.[0]; if (!feature) return; const [lon, lat] = feature.geometry.coordinates; if (state.marker) state.map.removeLayer(state.marker); state.marker = L.marker([lat, lon]).addTo(state.map).bindPopup(`<strong>${esc(row.label)}</strong><br>${nf.format(count(row))} entités`).openPopup(); state.map.setView([lat, lon], 11); } catch (error) { console.warn('Géocodage indisponible', error); } };
    const updateControls = () => { const select = document.getElementById('crm-map-department'); select.innerHTML = '<option value="">Tous les départements</option>' + (data.departments || []).map((row) => `<option value="${esc(row.label)}">${esc(row.label)} — ${nf.format(row.total)}</option>`).join(''); select.value = state.department; document.getElementById('crm-map-city-options').innerHTML = (data.cities || []).filter((row) => !state.department || row.department === state.department).slice(0, 500).map((row) => `<option value="${esc(row.label)}"></option>`).join(''); document.querySelectorAll('.crm-map-type').forEach((button) => button.classList.toggle('opacity-50', !state.types[button.dataset.type])); };
    state.map = L.map('crm-map', { scrollWheelZoom: true, preferCanvas: true }).setView([46.6, 2.4], 6);
    const tiles = L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', { maxZoom: 18, updateWhenIdle: true, keepBuffer: 2, attribution: '&copy; OpenStreetMap contributors' }).addTo(state.map);
    tiles.on('tileerror', (event) => console.warn('Tuile cartographique indisponible', event.coords));
    const resizeMap = () => window.requestAnimationFrame(() => state.map.invalidateSize({ animate: false }));
    window.addEventListener('resize', resizeMap);
    setTimeout(resizeMap, 100);
    setTimeout(resizeMap, 600);
    fetch('/vendor/maps/departements.geojson').then((response) => response.json()).then((geo) => { state.layer = L.geoJSON(geo, { style, onEachFeature: (feature, layer) => { layer.on('click', () => { state.department = feature.properties.code || feature.properties.nom || ''; state.city = ''; updateControls(); render(); }); layer.bindTooltip(`${feature.properties.code || ''} — ${feature.properties.nom || ''}`, { sticky: true }); } }).addTo(state.map); }).catch(() => {});
    const refreshFromApi = async () => {
        if (refreshing) return;
        refreshing = true;
        try {
            const response = await fetch('/ns-conseil/api/crm-map', { headers: { 'Accept': 'application/json', 'X-Requested-With': 'XMLHttpRequest' }, credentials: 'same-origin', cache: 'no-store' });
            if (!response.ok) throw new Error(`API ${response.status}`);
            data = await response.json();
            updateControls();
            render();
        } catch (error) { console.warn('Actualisation Carte CRM indisponible', error); }
        finally { refreshing = false; }
    };
    document.getElementById('crm-map-department').addEventListener('change', (event) => { state.department = event.target.value; state.city = ''; updateControls(); render(); }); document.getElementById('crm-map-city').addEventListener('change', (event) => { state.city = event.target.value; render(); geocode(); }); document.getElementById('crm-map-reset').addEventListener('click', () => { state.department = ''; state.city = ''; state.types = { prospects: true, clients: true, partenaires: true }; if (state.marker) { state.map.removeLayer(state.marker); state.marker = null; } updateControls(); render(); state.map.setView([46.6, 2.4], 6); }); document.querySelectorAll('.crm-map-type').forEach((button) => button.addEventListener('click', () => { state.types[button.dataset.type] = !state.types[button.dataset.type]; if (!types().length) state.types[button.dataset.type] = true; updateControls(); render(); })); document.getElementById('crm-map-departments').addEventListener('click', (event) => { const button = event.target.closest('[data-department]'); if (button) { state.department = button.dataset.department; state.city = ''; updateControls(); render(); } }); document.getElementById('crm-map-cities').addEventListener('click', (event) => { const button = event.target.closest('[data-city]'); if (button) { state.city = button.dataset.city; document.getElementById('crm-map-city').value = state.city; geocode(); } }); updateControls(); render();
    window.setInterval(refreshFromApi, 60000);
})();
</script>
